export const  LOGIN_ROUTE = '/login'
export const  REGISTRATION_ROUTE = '/registration'
export const  MAIN_ROUTE = '/'
export const  PUBLICATION_ROUTE = '/publication'
export const  AUTHORS_ROUTE = '/authors'
export const  THEMES_ROUTE = '/themes'
export const  REGIONS_ROUTE = '/regions'
export const  ADD_PUBLICATION_ROUTE = '/add_publication'
